# Generated by Django 5.2.7 on 2025-10-19 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssayTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('instruction_text', models.TextField(help_text='Instructions for the essay (e.g., word count, structure)')),
                ('word_count_min', models.IntegerField(default=300)),
                ('word_count_max', models.IntegerField(default=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Essay Topic',
                'verbose_name_plural': 'Essay Topics',
            },
        ),
        migrations.CreateModel(
            name='EssaySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('essay_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='essay_writing.essaytopic')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
