# Generated by Django 5.2.7 on 2025-10-19 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SynonymTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Synonym Topic',
                'verbose_name_plural': 'Synonym Topics',
            },
        ),
        migrations.CreateModel(
            name='SynonymResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Number of correct matches')),
                ('total', models.PositiveIntegerField(help_text='Total number of words in the topic')),
                ('percentage', models.FloatField(help_text='Score as percentage')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonym_results', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='match_synonyms.synonymtopic')),
            ],
            options={
                'verbose_name': 'Synonym Result',
                'verbose_name_plural': 'Synonym Results',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SynonymPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('synonym', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='match_synonyms.synonymtopic')),
            ],
            options={
                'unique_together': {('topic', 'word')},
            },
        ),
    ]
