# Generated by Django 5.2.7 on 2025-10-19 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillInBlankText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('instruction_text', models.TextField(default='Read the text below and fill in the blanks with appropriate words.')),
                ('text_content', models.TextField(help_text="Use '[[BLANK]]' for each blank.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FillInBlankTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fill-in-the-Blank Topic',
                'verbose_name_plural': 'Fill-in-the-Blank Topics',
            },
        ),
        migrations.CreateModel(
            name='FillInBlankResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Number of correct answers')),
                ('total', models.PositiveIntegerField(help_text='Total number of blanks')),
                ('percentage', models.FloatField(help_text='Score as percentage')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_in_blank_results', to=settings.AUTH_USER_MODEL)),
                ('fill_in_blank_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='fill_in_blanks.fillinblanktext')),
            ],
            options={
                'verbose_name': 'Fill-in-the-Blank Result',
                'verbose_name_plural': 'Fill-in-the-Blank Results',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='fillinblanktext',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='fill_in_blanks.fillinblanktopic'),
        ),
        migrations.CreateModel(
            name='BlankAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_index', models.IntegerField(help_text='Position of the blank (0-indexed)')),
                ('correct_answer', models.CharField(max_length=200)),
                ('fill_in_blank_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='fill_in_blanks.fillinblanktext')),
            ],
            options={
                'unique_together': {('fill_in_blank_text', 'blank_index')},
            },
        ),
    ]
